# iso_639_2_languages.py

iso_639_2_languages = [
    ("aar", "Afar (aar)"),
    ("abk", "Abkhazian (abk)"),
    ("ave", "Avestan (ave)"),
    ("afr", "Afrikaans (afr)"),
    ("aka", "Akan (aka)"),
    ("amh", "Amharic (amh)"),
    ("arg", "Aragonese (arg)"),
    ("ara", "Arabic (ara)"),
    ("asm", "Assamese (asm)"),
    ("ava", "Avaric (ava)"),
    ("aym", "Aymara (aym)"),
    ("aze", "Azerbaijani (aze)"),
    ("bak", "Bashkir (bak)"),
    ("bel", "Belarusian (bel)"),
    ("bul", "Bulgarian (bul)"),
    ("bis", "Bislama (bis)"),
    ("bam", "Bambara (bam)"),
    ("ben", "Bengali (ben)"),
    ("tib", "Tibetan (tib)"),
    ("bod", "Tibetan (bod)"),
    ("bre", "Breton (bre)"),
    ("bos", "Bosnian (bos)"),
    ("cat", "Catalan; Valencian (cat)"),
    ("che", "Chechen (che)"),
    ("cha", "Chamorro (cha)"),
    ("cos", "Corsican (cos)"),
    ("cre", "Cree (cre)"),
    ("ces", "Czech (ces)"),
    ("cze", "Czech (cze)"),
    ("chu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic (chu)"),
    ("chv", "Chuvash (chv)"),
    ("cor", "Cornish (cor)"),
    ("cym", "Welsh (cym)"),
    ("wel", "Welsh (wel)"),
    ("dan", "Danish (dan)"),
    ("ger", "German (ger)"),
    ("deu", "German (deu)"),
    ("div", "Divehi; Dhivehi; Maldivian (div)"),
    ("dzo", "Dzongkha (dzo)"),
    ("ewe", "Ewe (ewe)"),
    ("gre", "Greek, Modern (1453-) (gre)"),
    ("ell", "Greek, Modern (1453-) (ell)"),
    ("eng", "English (eng)"),
    ("epo", "Esperanto (epo)"),
    ("spa", "Spanish; Castilian (spa)"),
    ("est", "Estonian (est)"),
    ("baq", "Basque (baq)"),
    ("eus", "Basque (eus)"),
    ("per", "Persian (per)"),
    ("fas", "Persian (fas)"),
    ("ful", "Fulah (ful)"),
    ("fin", "Finnish (fin)"),
    ("fij", "Fijian (fij)"),
    ("fao", "Faroese (fao)"),
    ("fra", "French (fra)"),
    ("fre", "French (fre)"),
    ("fry", "Western Frisian (fry)"),
    ("gle", "Irish (gle)"),
    ("gla", "Gaelic; Scottish Gaelic (gla)"),
    ("glg", "Galician (glg)"),
    ("glv", "Manx (glv)"),
    ("grn", "Guarani (grn)"),
    ("guj", "Gujarati (guj)"),
    ("glv", "Manx (glv)"),
    ("hau", "Hausa (hau)"),
    ("heb", "Hebrew (heb)"),
    ("hin", "Hindi (hin)"),
    ("hmo", "Hiri Motu (hmo)"),
    ("hrv", "Croatian (hrv)"),
    ("hat", "Haitian; Haitian Creole (hat)"),
    ("hun", "Hungarian (hun)"),
    ("hye", "Armenian (hye)"),
    ("arm", "Armenian (arm)"),
    ("her", "Herero (her)"),
    ("ina", "Interlingua (International Auxiliary Language Association) (ina)"),
    ("ind", "Indonesian (ind)"),
    ("ile", "Interlingue; Occidental (ile)"),
    ("ibo", "Igbo (ibo)"),
    ("iii", "Sichuan Yi; Nuosu (iii)"),
    ("ipk", "Inupiaq (ipk)"),
    ("ido", "Ido (ido)"),
    ("isl", "Icelandic (isl)"),
    ("ice", "Icelandic (ice)"),
    ("ita", "Italian (ita)"),
    ("iku", "Inuktitut (iku)"),
    ("jpn", "Japanese (jpn)"),
    ("jav", "Javanese (jav)"),
    ("kal", "Kalaallisut; Greenlandic (kal)"),
    ("kan", "Kannada (kan)"),
    ("kau", "Kanuri (kau)"),
    ("kas", "Kashmiri (kas)"),
    ("kaz", "Kazakh (kaz)"),
    ("khm", "Central Khmer (khm)"),
    ("kik", "Kikuyu; Gikuyu (kik)"),
    ("kin", "Kinyarwanda (kin)"),
    ("kir", "Kirghiz; Kyrgyz (kir)"),
    ("kom", "Komi (kom)"),
    ("kon", "Kongo (kon)"),
    ("kor", "Korean (kor)"),
    ("kur", "Kurdish (kur)"),
    ("kua", "Kuanyama; Kwanyama (kua)"),
    ("lat", "Latin (lat)"),
    ("ltz", "Luxembourgish; Letzeburgesch (ltz)"),
    ("lug", "Ganda (lug)"),
    ("lim", "Limburgan; Limburger; Limburgish (lim)"),
    ("lin", "Lingala (lin)"),
    ("lao", "Lao (lao)"),
    ("lit", "Lithuanian (lit)"),
    ("lub", "Luba-Katanga (lub)"),
    ("lav", "Latvian (lav)"),
    ("mlg", "Malagasy (mlg)"),
    ("mah", "Marshallese (mah)"),
    ("mao", "Maori (mao)"),
    ("mri", "Maori (mri)"),
    ("mac", "Macedonian (mac)"),
    ("mkd", "Macedonian (mkd)"),
    ("mal", "Malayalam (mal)"),
    ("mon", "Mongolian (mon)"),
    ("mar", "Marathi (mar)"),
    ("may", "Malay (may)"),
    ("msa", "Malay (msa)"),
    ("mlt", "Maltese (mlt)"),
    ("bur", "Burmese (bur)"),
    ("mya", "Burmese (mya)"),
    ("nau", "Nauru (nau)"),
    ("nob", "Bokmål, Norwegian; Norwegian Bokmål (nob)"),
    ("nde", "Ndebele, North; North Ndebele (nde)"),
    ("nep", "Nepali (nep)"),
    ("ndo", "Ndonga (ndo)"),
    ("nno", "Nynorsk, Norwegian; Norwegian Nynorsk (nno)"),
    ("nor", "Norwegian (nor)"),
    ("iii", "Sichuan Yi; Nuosu (iii)"),
    ("nbl", "Ndebele, South; South Ndebele (nbl)"),
    ("nav", "Navajo; Navaho (nav)"),
    ("nya", "Chichewa; Chewa; Nyanja (nya)"),
    ("oci", "Occitan (post 1500); Provençal (oci)"),
    ("oji", "Ojibwa (oji)"),
    ("orm", "Oromo (orm)"),
    ("ori", "Oriya (ori)"),
    ("oss", "Ossetian; Ossetic (oss)"),
    ("pan", "Panjabi; Punjabi (pan)"),
    ("pli", "Pali (pli)"),
    ("pol", "Polish (pol)"),
    ("pus", "Pushto; Pashto (pus)"),
    ("por", "Portuguese (por)"),
    ("que", "Quechua (que)"),
    ("roh", "Romansh (roh)"),
    ("run", "Rundi (run)"),
    ("ron", "Romanian; Moldavian; Moldovan (ron)"),
    ("rum", "Romanian; Moldavian; Moldovan (rum)"),
    ("rus", "Russian (rus)"),
    ("sag", "Sango (sag)"),
    ("san", "Sanskrit (san)"),
    ("sin", "Sinhala; Sinhalese (sin)"),
    ("slk", "Slovak (slk)"),
    ("slo", "Slovak (slo)"),
    ("slv", "Slovenian (slv)"),
    ("smo", "Samoan (smo)"),
    ("sna", "Shona (sna)"),
    ("snd", "Sindhi (snd)"),
    ("som", "Somali (som)"),
    ("sot", "Sotho, Southern (sot)"),
    ("spa", "Spanish; Castilian (spa)"),
    ("sun", "Sundanese (sun)"),
    ("swa", "Swahili (swa)"),
    ("ssw", "Swati (ssw)"),
    ("swe", "Swedish (swe)"),
    ("tam", "Tamil (tam)"),
    ("tel", "Telugu (tel)"),
    ("tgk", "Tajik (tgk)"),
    ("tha", "Thai (tha)"),
    ("tir", "Tigrinya (tir)"),
    ("tuk", "Turkmen (tuk)"),
    ("tgl", "Tagalog (tgl)"),
    ("tsn", "Tswana (tsn)"),
    ("ton", "Tonga (Tonga Islands) (ton)"),
    ("tur", "Turkish (tur)"),
    ("tso", "Tsonga (tso)"),
    ("tat", "Tatar (tat)"),
    ("twi", "Twi (twi)"),
    ("tah", "Tahitian (tah)"),
    ("uig", "Uighur; Uyghur (uig)"),
    ("ukr", "Ukrainian (ukr)"),
    ("urd", "Urdu (urd)"),
    ("uzb", "Uzbek (uzb)"),
    ("ven", "Venda (ven)"),
    ("vie", "Vietnamese (vie)"),
    ("vol", "Volapük (vol)"),
    ("wln", "Walloon (wln)"),
    ("wol", "Wolof (wol)"),
    ("xho", "Xhosa (xho)"),
    ("yid", "Yiddish (yid)"),
    ("yor", "Yoruba (yor)"),
    ("zha", "Zhuang; Chuang (zha)"),
    ("zul", "Zulu (zul)")
]